### ISSUE TITLE
Store the url property of items in the replacement dictionary to be available to other templates in the solution

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#457]
Currently we store the item id of as a replaceable variable so that it can be swizzled in other items. For example:

{{cd4e7edbca5c428a86e755e701a438b5.itemId}} 

This request would be to also add the url property of the item to the replacement dictionary:

{{cd4e7edbca5c428a86e755e701a438b5.url}}

This is necessary for items like web experiences because the url can change between Online and Enterprise. In my example, I had a Hub site referencing a web experience and there was no way to create a variable that could be replaced and be accurate for both Enterprise and Online.

**Comment by MikeTschudi** [comment]
@chris-fox, would you please expand on this? Is it like #477, except that for each item with a URL (e.g., a Web Map), we add a template-dictionarly mapping from the [Web Map's] URL to {{*webmap_id*.url}} for replacing the URL in other items?

**Comment by chris-fox** [comment]
@MikeTschudi, yes that's exactly right. Some items like Experience Builder apps have complex logic for resolving their url so it works in Online and Enterprise. So after that is resolved it would be good to store that url in the template-dictionary, so that any items that want to reference it and just use the {{itemid.url}} variable to resolve it.

**Comment by chris-fox** [comment]
@MikeTschudi, been testing this and it doesn't seem to be working the way I would expect. The solution below has a web map that in its item description has the following:

{{fcb2bf2837a6404ebb418a1f805f976a.url}} <div>{{cefb7d787b8b4edb971efba758ee0c1e.url}}</div>

These are references to a Web AppBuilder and Experience Builder app items that are dependencies of the web map. When I deploy those variables are not being replaced with the url's of the apps even those items do have a url property.

https://www.arcgis.com/home/item.html?id=9e59550a94914f9b8a5e71814968bc35

**Comment by MikeTschudi** [comment]
@chris-fox, got it. Implemented url addition only to solution creation as with #477. Will add to deployment. Thanks for the example!

**Comment by chris-fox** [comment]
@MikeTschudi, that was going to be my next request to get this implemented in the post process workflow during creation as well. So that's great. I will test this out as well.

**Comment by chris-fox** [comment]
Hi @MikeTschudi, I was testing this implementation of the item url property during solution creation with #477 and it is not working as I would expect. You can repro with the following group:

https://localdeployment.maps.arcgis.com/home/group.html?id=04f36eae6346438c873a461da54c4a2f

In the group is a web map and in its item description is the following text:

https://experience.arcgis.com/experience/fcb2bf2837a6404ebb418a1f805f976a<div>https://localdeployment.maps.arcgis.com/apps/webappviewer/index.html?id=cefb7d787b8b4edb971efba758ee0c1e</div>

When I create the solution from the group, this is what is written to the solution item for that web map's item description:

https://experience.arcgis.com/experience/{{fcb2bf2837a6404ebb418a1f805f976a.itemId}}<div>{{portalBaseUrl}}/apps/webappviewer/index.html?id={{cefb7d787b8b4edb971efba758ee0c1e.itemId}}</div>

I would expect it to be:

{{fcb2bf2837a6404ebb418a1f805f976a.url}}<div>{{cefb7d787b8b4edb971efba758ee0c1e.url}}</div>

I am wondering if its an order of operations. We should check for url's first before checking for item ids or the portal base url, because if we don't want to swap out the item ids and portal base url of what could be a url.

**Comment by MikeTschudi** [comment]
@chris-fox, the two forms produce the same result upon deployment *if the two items in the description are dependencies of the web map*. Because they're not dependencies of Test Map, the web map is created in parallel with the other items, and so `fcb2bf2837a6404ebb418a1f805f976a.itemId` and `cefb7d787b8b4edb971efba758ee0c1e.itemId` are not defined when the web map is deployed. So with PR #525, this issue is resolved?

**Comment by chris-fox** [comment]
@MikeTschudi, I tested and verified that variables like {{fcb2bf2837a6404ebb418a1f805f976a.url}} are properly replaced during deployment now. Thank you.

There is still an issue with the variables not being properly set during creation, and the fact that the items have to be a dependency seems like something we should resolved during post processing, but I will log different issues for these. Thanks.
